### ISSUE TITLE
Absichern der Schreib API

### ISSUE THREAD

**Issue by Niklas345** [testbefund/meta#1]
Zur Zeit ist die Schreib-API nicht gesichert. Die wahrscheinlichkeit, Zufällig einen Schreiboperation durchzuführen liegt zwar bei 1:1.000.000.000 (uuidv4 Konfliktchance), allerdings muss das nicht sein.

Die Schreibzugriffe kann im Zweifelsfall nur das testende Labor durchführen. Das passiert durch ausgegebene Geräte. 

Wir könnten eine Gerätebindung an der Schreib-API einführen.

**Comment by florianb** [comment]
Ich würde sogar einen Schritt weiter gehen und Organistions-Accounts anlegen - unter denen dann Geräte registriert werden müssen. Das würde in Zukunft auch erlauben:

- Organisationen bei Missbrauch zu sperren.
- Für Organisationen wichtige Informationen gesondert zu behandeln, bspw in Zukunft einen Lesezugriff für die staatlich beauftragten Gesundheitsorganisationen einzurichten. Oder für Organisationen wichtige, zusätzliche Informationen zu verwalten.

**Comment by Niklas345** [comment]
Vorschlag:

- Nutzername/Passwort mit Spring Security

**Comment by florianb** [comment]
:+1:  Reicht für's erste - mfa lässt sich ggf nachrüsten..

**Comment by Niklas345** [comment]
Nutzername + Passwort Protection gibt es. Alles weitere funktioniert über https://github.com/1-011-c/meta/issues/13
