### ISSUE TITLE
Video mit UseCase-Erklärung

### ISSUE THREAD

**Issue by ANusselt** [testbefund/meta#17]
Wir brauchen ein Video, welches einfach erklärt, welchen Mehrwert wir mit Testbefund liefern.

**Comment by ANusselt** [comment]
Video auf Youtube geladen, in DevPost ausgetauscht und auf Webseite gestellt

https://youtu.be/-7sHeqAJCao

**Comment by florianb** [comment]
Sieht gut aus! Vielen Dank für die Arbeit!
