### ISSUE TITLE
Grafisch ansprechende Webseite für Testbefund

### ISSUE THREAD

**Issue by ANusselt** [testbefund/meta#18]
eine Webseite, die die UseCases transportiert und schnell erklärt, worum es geht

**Comment by ANusselt** [comment]
Website ist soweit fertiggestellt unter http://testbefund.nusselt.de

 @florianb besteht eine Möglichkeit, sie auf die offizielle Domain zu linken und evtl. eine offizielle EMail-Adresse einzurichten?

**Comment by florianb** [comment]
@ANusselt - klar - schick mir bitte mal die IP-Adresse, die ich eintragen soll. Je nach Hoster musst du ggf. noch die Domain im Webserver hinterlegen..

**Comment by ANusselt** [comment]
@florianb  Domain ist hinterlegt und IP hab ich dir geschickt ;) (LinkedIn)

**Comment by florianb** [comment]
Nice - vielen Dank!
