### ISSUE TITLE
Updaten des Datenmodells

### ISSUE THREAD

**Issue by Niklas345** [testbefund/meta#2]
Unser Datenmodell ist zur Zeit ja relativ einfach. Es stehen nicht viele Informationen zur Verfügung. 

Vor dem Hintergrund, dass wir diverse Test-Typen haben können, müssten wir das erweitern. 

Ziel dieses Items soll es sein festzustellen...

- Welche Daten wir brauchen
- Welche Daten wir mit unserem Konzept speichern können
- Wie wir ggfs. andere Daten speichern

**Comment by florianb** [comment]
~~Finde ich gut - sollen wir mit der Arbeit ohne einen echten Anwender anfangen?~~
Habe gerade Discord gelesen. :smile_cat:

**Comment by Niklas345** [comment]
- Zu testende Organisation + Addresse
- Telefonnumer (Kontakt im Positivfeld)
- Email
- Geschäftszeiten
- Link zur Landing Page

Für Aidshilfe relevant

**Comment by Tandashi** [comment]
> * Zu testende Organisation + Addresse
> * Telefonnumer (Kontakt im Positivfeld)
> * Email
> * Geschäftszeiten
> * Link zur Landing Page
> 
> Für Aidshilfe relevant

Sollen diese Sachen wirklich in das Daten model? Waren die nicht für das frontend gedacht (#8)?

Hätte das sonst auch mal nen Draft in Form eines JSON Schema gemacht, wie ich denke, dass man das ganze abbilden könnte. Ersmal mit dem Ansatzt einer Art Finite-State Machine von @Niklas345 aus #5.

Den `title` eines `test` könnte man auch hier wieder durch einen Enum austauschen habe es aber erstmal simpel gehalten.

Der Hintergrund hinter einer `uuid_write` für jeden Test ist der, dass mehrere Labore  auf verschiedene Krankheiten testen und diese nicht die Möglichkeit haben sollen das Ergebniss eines anderen Tests zu verändern. Man könnte hier das ganze aber auch wieder auf eine "globale" `uuid_write` reduzieren, wenn wir sagen, dass dies ein Fall ist welchen wir nicht berücksichtigen müssen.

### test.schema.json
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    
    "title": "Testcase Schema",
    "description": "Testcase Schema for testbefund",

    "additionalProperties": false,
    "properties": {
        "title": {
            "type": "string"
        },
        "uuid_write": {
            "type": "string"
        },
        "infected": {
            "type": "string",
            "enum": [
                "POSITIVE",
                "NEGATIVE",
                "UNKNOWN"
            ]
        },
        "status": {
            "type": "string",
            "enum": [
                "IN_PROGRESS",
                "REVIEW_PENDING",
                "DONE"
            ]
        }
    },
    "required": [
        "title",
        "uuid_write",
        "infected",
        "status"
    ]
}
```

### testcase.json
```json
{
    "$schema": "./testcase.schema.json",
    "uuid_read": "r1",
    "date": "2002-10-02T10:00:00Z",
    "tests": [
        {
            "title": "Corona Test",
            "infected": "NEGATIVE",
            "status": "REVIEW_PENDING",
            "uuid_write": "k1"
        },
        {
            "title": "HIV Test",
            "infected": "POSITIVE",
            "status": "DONE",
            "uuid_write": "k2"
        },
        {
            "title": "Mums Test",
            "infected": "UNKNOWN",
            "status": "IN_PROGRESS",
            "uuid_write": "k3"
        }
    ]
}
```

### testcase.schema.json
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "Testcase Container Schema",
    "description": "Testcase Container Schema for testbefund",

    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "uuid_read": {
            "type": "string"
        },
        "date": {
            "type": "string",
            "format": "date-time"
        },
        "tests": {
            "type": "array",
            "items": {
                "$ref": "./test.schema.json"
            }
        }
    },
    "required": [
        "uuid_read",
        "date",
        "tests"
    ]
}
```

**Comment by florianb** [comment]
Wir sollten davon ausgehen, dass sich die weichen Informationen "häufig" ändern und durch den entsprechenden Mandanten (langfristig) editierbar sein sollten.

Ich würde das vollständig in eine eigene DB auslagern und in Zukunft ein eigenes Interface für die Mandanten vorsehen.

**Comment by florianb** [comment]
Ich füge mal meinen Entwurf aus #5 hier ein - ist wohl der bessere Platz:

```yaml
coronaTestCase:
  read_id: 58XzRgVQk30ohSESuANwIZ
  write_ids:
   - RohmLrxs7mfJnj4-3GdrE1
  states:
   - write_id: xgK9lceRaHIdR6V5Wne_mo
     timestamp: 2007-08-31T16:47+00:00
     state: issued
   - write_id: RohmLrxs7mfJnj4-3GdrE1
     timestamp: 2007-08-31T16:47+00:00
     state: inbox
   - write_id: RohmLrxs7mfJnj4-3GdrE1
     timestamp: 2007-08-31T16:47+00:00
     state: testStart
```

Vorteile:
- Flexible Prozessgestaltung
- Mehrere "Labore" möglich

**Comment by Niklas345** [comment]
Hey @florianb ,
Finde ich sinnvoll, lass uns das erstmal so implementieren.

**Comment by Tandashi** [comment]
Hätte sonst auch nochmal ne V2 meines Drafts von vorher.
Sollte schon die Informationen aus #9 enthalten und es sollte auch leicht möglich sein damit #1 umzusetzten. Zudem ist es damit einfach möglich mehrere Tests abzubilden.

Ist jedoch noch nicht mit @florianb art umgesetzt aber hier sollte es ja nicht schwer sein den `status` durch seine mehr oder weniger "history" zu ersetzen.

**Sidenote**: `data.json` enthält ein komplett populateten Datensatz. Man würde natürlich die verschiedenen Teile: `client`, `test`, `testcontainer`, [`openinghour`] in einzelne Tabellen aufteilen.

**client.schema.json**
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    
    "title": "Client Schema",
    "description": "The schema for a testbefund client",

    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "address": {
            "type": "string"
        },
        "telefon": {
            "type": "string"
        },
        "email": {
            "type": "string",
            "format": "email"
        },
        "opening_hours": {
            "type": "array",
            "items": {
                "$ref": "./openinghour.schema.json"
            }
        },
        "homepage": {
            "type": "string",
            "format": "uri"
        }
    },
    "required": [
        "id",
        "name",
        "address",
        "telefon",
        "email",
        "opening_hours",
        "homepage"
    ]
}
```

**openinghour.schema.json**
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    
    "title": "Opening Hour Schema",
    "description": "The schema for a opening hour definition",

    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string"
        },
        "from": {
            "type": "string",
            "pattern": "^((?:[01]\\d|2[0-3]):[0-5]\\d$)"
        },
        "till": {
            "type": "string",
            "pattern": "^((?:[01]\\d|2[0-3]):[0-5]\\d$)"
        },
        "day": {
            "type": "string",
            "enum": [
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "STATURDAY",
                "SUNDAY"
            ]
        }
    },
    "required": [
        "id",
        "from",
        "till",
        "day"
    ]
}
```

**test.schema.json**
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    
    "title": "Testcase Schema",
    "description": "Testcase Schema for testbefund",

    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string"
        },
        "uuid_write": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "client": {
            "type": "object",
            "$ref": "./client.schema.json"
        },
        "infected": {
            "type": "string",
            "enum": [
                "POSITIVE",
                "NEGATIVE",
                "UNKNOWN"
            ]
        },
        "status": {
            "type": "string",
            "enum": [
                "IN_PROGRESS",
                "REVIEW_PENDING",
                "DONE"
            ]
        }
    },
    "required": [
        "id",
        "uuid_write",
        "title",
        "client",
        "infected",
        "status"
    ]
}
```
**testcontainer.schema.json**
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "Testcase Container Schema",
    "description": "Testcase Container Schema for testbefund",

    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "uuid_read": {
            "type": "string"
        },
        "date": {
            "type": "string",
            "format": "date-time"
        },
        "tests": {
            "type": "array",
            "items": {
                "$ref": "./test.schema.json"
            }
        }
    },
    "required": [
        "uuid_read",
        "date",
        "tests"
    ]
}
```
**data.json**
```json
{
    "$schema": "./testcontainer.schema.json",
    "uuid_read": "r1",
    "date": "2002-10-02T10:00:00Z",
    "tests": [
        {
            "id": "t1",
            "uuid_write": "w1",
            "title": "Corona Test",
            "client": {
                "id": "c1",
                "name": "Client 1",
                "address": "Address",
                "email": "client@client.de",
                "telefon": "0123456789",
                "opening_hours": [
                    {
                        "id": "h1",
                        "day": "MONDAY",
                        "from": "08:00",
                        "till": "10:00"
                    },
                    {
                        "id": "h2",
                        "day": "TUESDAY",
                        "from": "07:00",
                        "till": "12:00"
                    }
                ],
                "homepage": "https://github.com"
            },
            "infected": "UNKNOWN",
            "status": "IN_PROGRESS"
        },
        {
            "id": "t2",
            "uuid_write": "w2",
            "title": "HIV Test",
            "client": {
                "id": "c2",
                "name": "Client 2",
                "address": "Address",
                "email": "client2@client.de",
                "telefon": "0123456789",
                "opening_hours": [
                    {
                        "id": "h3",
                        "day": "MONDAY",
                        "from": "08:00",
                        "till": "10:00"
                    },
                    {
                        "id": "h4",
                        "day": "TUESDAY",
                        "from": "07:00",
                        "till": "12:00"
                    }
                ],
                "homepage": "https://github.com"
            },
            "infected": "POSITIVE",
            "status": "DONE"
        }
    ]
}
```

**Comment by florianb** [comment]
Finde ich gut,
- die öffentlichen Informationen zu normalisieren.

Anregungen:
- Alle Zeitangaben sollten mit einer Timezone versehen sein.
- Besser `_id` statt `_uuid` - wir sollten uns auf Ids als `String` einstellen.
- Statt `Title`sopllten wir vielleicht auch eine medizinische Standard-Referenz hinterlegen gegen die der Test , vielleicht den [ICD](https://icd.who.int/browse11/l-m/en): `"icd_label": "1C62"`. Eventuell gibt es auch eine bestimmte Test-Bezeichnung (allein für HIV gibt's mindesetns vier verschiedene Testarten). Da kann ich mal nachfragen, sobald ich den Laborkontakt habe.

**Comment by Niklas345** [comment]
Client passt für mich.

Für Openinghours - warum nicht einfach als freitext string? Standardisierung ist zwar gut, macht die Eingabe der Daten aber frimmelig. Dazu kommt dann ein recht großer Validierungsaufwand, da eine Fehlermeldung "Regex passt nicht" nicht wirklich aussagekräftig ist. 

test + testcontainer passt so für mich auch.

**Comment by Tandashi** [comment]
~Bei der Zeitangabe geben ich dir vollkommen recht,da sollte man eine Zeitzone mit hinterlegen. Du meintest hier bestimmt die Öffnungszeiten richtig? Da war ich mir unsicher wie genau man das gut umsetzen kann da `datetime` für mich nicht so viel Sinn ergeben hat. Man es geht ja nicht um einen explizieten Tag und immer `1970-01-01` mit zu speichern fande ich etwas unnötigen overhead. Oder gibt es für genau soetwas auch ein Standart-Format?~  

Siehe @Niklas345 Ansatz 

Die `id` in dem Draft sollte nur die Datenbank ID wiederspiegel. `_id` als `uuid_write`/`uuid_read` zuverwenden könnte je nach Datenbank schwierig werden, da MongoDB z.B. dessen Document ID's als `_id` speichert.  Oder habe ich dich hier falsch verstanden?

Der `title` war dafür gedacht, dass man dem Benutzer später anzeigen kann, um welchen Test es sich handel. Ich glaube der kann mit der ICD nicht so viel anfangen. Man könnte aber beides meiner Meinung nach hinterlegen. Also sowohl `title` als "leserliche" Referenz und die ICD für die Labore etc.

**Comment by florianb** [comment]
Just for info: Was die Zeitangabe angeht hast du recht, bei reinen Zeitangaben wäre das m.E. ISO-konform `12:00:00+01:00`.

Und du hast recht `id` einzeln wäre vielleicht eine Datenbank-ID, ich habe in #3 vorgeschlagen UUIDs für read/write zu ersetzen. Das obig geschriebene `_id` ist ein freudscher Versprecher - ich bin es gewohnt das ID anzuhängen also bspw. `read_id` statt `id_read` zu schreiben. Aber grundsätzlich sollte an der Stelle `uuid` durch `id` ersetzt werden, um Mißverständnissen vorzubeugen.

Deine Anmerkung zum Thema Title ist korrekt. Eine Konsequenz zum Einsatz einer Norm-ID wäre tatsächlich auch ein die Einführung einer Übersetzungs-Tabelle. Abgesehen vom Overhead (wenn Prosa im Datensatz landet) möchte ich vermeiden, dass jedes Labor, jeder Mandant seine eigenen Angaben formuliert. Das ist aber wohlgemerkt keine dringliche Angelegenheit und könnte auch später implementiert werden (wobei ich bei einer Übersetzungstabelle auch erstmal nur mit dem einen, den zwei Fällen beginnen würde, die für uns relevant sind).

**Comment by Niklas345** [comment]
Datenmodell ist so auf der neuen API angepasst, siehe https://github.com/1-011-c/testbefund-api
