### ISSUE TITLE
Wechsel zu NanoID

### ISSUE THREAD

**Issue by florianb** [testbefund/meta#3]
Zusätzlich zu @Niklas345 Punkten in #1 und #2 schlage ich vor anstelle der UUIDv4 [NanoId](https://zelark.github.io/nano-id-cc/) einzusetzen, um die Kollisionswahrscheinlichkeit weiter zu reduzieren.

**Comment by florianb** [comment]
Vermutlich macht es auch Sinn, anstelle des `corona-test-case`-pfads eher zu einem versions-basierten pfad zu wechseln, z.B.: `/v1/qJwHuBDFnoExSS5VqSybR`

**Comment by florianb** [comment]
Der Vorschlag hat nur Bestand, wenn mit der binären Speicherung einer UUID keine außerordentliche Vorteile einhergehen.

**Comment by Niklas345** [comment]
@florianb 
Wollen wir das Thema API Versioning als separten Punkt aufnehmen?

**Comment by Niklas345** [comment]
Zum Thema UUIDv4 vs NanoID. Ich bin eigentlich immer ein Fan davon, Standards zu verwenden, sehe aber auch kein Problem darin, NanoID zu nehmen. Beide sind ja grundsätzlich interchangeable.

**Comment by Niklas345** [comment]
@florianb sollen wir die read/write IDs noch ändern? Die sind zur Zeit mit der Java UUID Standard implementierung erstellt. Die sollten auf SecureRandom basieren:
https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html

**Comment by florianb** [comment]
Ich würds machen: https://github.com/aventrix/jnanoid
aber wir können damit noch warten wenn du magst?

**Comment by Niklas345** [comment]
Nöööö, bau ich direkt morgen ein! Ich mach die länge des keys dann über eine Env konfigurierbar.

**Comment by Niklas345** [comment]
Done. 
Commit: https://github.com/1-011-c/testbefund-api/commit/f8f0ab7896eab9465dfa24c4d90e9c1899631383

**Comment by florianb** [comment]
@Niklas345 - nice job! Vielen Dank!
