### ISSUE TITLE
Reduktion auf eine Tracking-ID

### ISSUE THREAD

**Issue by florianb** [testbefund/meta#4]
Möglicherweise ließe sich die Verwendung der Tracking-IDs auf eine einzige ID-verringern.

In Verbindung mit Organisations-Accounts (wie in #1 vorgeschlagen) ist es vielleicht möglich anstelle von zwei unterschiedlichen Tracking-IDs nur eine einzelne zu verwenden. Die Änderung am Datensatz bliebe dann den dafür legitimierten Organisationen vorbehalten.

**Comment by Niklas345** [comment]
Ich denke, der Ausbau der zweiten Tracking ID würde einen Möglichen Angriffsvektor ermöglichen.

Zur Zeit ist unser System durch das Design relativ sicher, selbst wenn der User seine Daten verliert. 

Die Reduktion auf eine ID würde jetzt einen zentralen Mechanismus aushebeln. Klar. Wenn wir eine Device-Bindung durch ausgegeben Geräte haben, dann haben wir auch keinen Angriffspunkt. Aber wenn dann doch mal die Device-Bindung umgangen werden kann, dann greift unser Security-By-Design Konzept nicht mehr.

Da es nicht schadet, 2 IDs zu haben (der eine Index mehr kostet uns irgendwie 1,50€ im Monat in der DynamoDB), würde ich die einfach so drin lassen.

tl;dr: Ich sehe keine nennensewerten Vorteile

**Comment by HerrSchwarz** [comment]
Ich sehe auch keinen Vorteil. Wir müssten trotzdem zwei Aufkleber drucken, darum kommen wir so oder so nicht drumrum.

**Comment by florianb** [comment]
Ja ihr habt - recht, erhöht auch einfach die Angrifssfläche.
