### ISSUE TITLE
Api-Versioning

### ISSUE THREAD

**Issue by florianb** [testbefund/meta#6]
Die (vermutlich auch weiterhin nicht ausbleibenden) Änderungen an der API sollten sich explizit an allen Endpunkten ablesen lassen, um die wartbarkeit zu erhöhen, ich schlage deshalb vor ein versionsbasiertes Pfad-Schema einzuführen:

`/v{majorVersion}/{trackingId}`

**Comment by Niklas345** [comment]
Erstmal ganz einfach Imlementiert mit https://github.com/1-011-c/testbefund-api/commit/ede1ced78caa175784cac6547820f1f227a989b4
