### ISSUE TITLE
Organisationen Verwalten

### ISSUE THREAD

**Issue by Niklas345** [testbefund/meta#9]
Wir brauchen eine Möglichkeit, Organisationen anzulegen, zu verwalten und zu löschen (CRUD).

Eine Organisation besteht aus folgenden Feldern:

- Name
- Telefonnummer
- Email
- Geschäftszeiten
- Link zur Landing Page / Homepage

(Es handelt sich dabei um öffentlich Zugängliche Daten)

**Comment by florianb** [comment]
Für welche Zwecke wollen wir den Eintrag verwenden können?

**Comment by Niklas345** [comment]
@florianb ,
Ich würde das an den Test Case anfügen. Ziel ist es, Organisations Meta-Informationen zu Hinterlegen, die dann im Frontend angezeigt werden können,

**Comment by florianb** [comment]
Achso ja gut - sollte vermutlich auch in eine eigene Tabelle.

Für's Pflege-Frontend können wir auch eine PWA skizzieren - solltge keine große Sache sein. Einzig die Authentifizierung wird interessant - wir müssten bei klassischem Vorgehen Accounts und die Möglichkeit zur Erstellung der ersten Basisaccounts bereitstellen.

Oder wir pflegen die DB per Dump.

**Comment by Niklas345** [comment]
Umgesetzt + UI durch swagger-ui bereitgestellt
https://github.com/1-011-c/testbefund-api/commit/468970681a5f8941a2d23ef9c1da5a2a21344b5d
